#ifndef IRC_H
#define IRC_H

#include <iostream>
#include "../../algorithms/SMC/sliding_mode_controller.h"
#include "../../models/admittance/admittance_model.h"
#include "../../observers/NDO/nonlinear_disturbance_observer.h"

/*
equation:
Wearer:
  equation:
    - error_r = degree_r - degree
    - torque_h = PD(error_r)
torque_e = IRC(degree)
    IRC:
    equation:
        - torque_h_hat = NDOB(degree, degree_dot, torque_e)
        - degree_d = Admittance(torque_h_hat) -> Impedance controller
        - error_d = degree_d - degree 
        - torque_e = SMC(error_d, degree_dot, torque_h_hat)
Human_Exoskeleton: (Output)
  equation:
    - degree = Plant(torque_h + torque_e)

Notation:
  Signals:
    degree_r: Reference (desired) joint angle
    degree: Measured exoskeleton joint angle
    degree_d: Desired joint angle generated by the admittance model
    degree_dot: Joint angular velocity

  Errors:
    error_r: Reference tracking error (degree_r - degree)
    error_d: Admittance tracking error (degree_d - degree)

  Torques:
    torque_h: Human-applied torque
    torque_h_hat: Estimated human-applied torque
    torque_e: Exoskeleton actuator torque

  Controllers:
    PD: Wearer PD controller
    NDOB: Nonlinear Disturbance Observer
    Admittance: Desired admittance model
    SMC: Sliding Mode Controller
    Plant: Human–Exoskeleton dynamics
*/
struct IRCParams
{
    admittanceParams admittance;

    double lambda;
    double eta;
    double fi;
    double D;

    double observerGain;
    double dt;
};
struct RobotState
{
    double degree;
    double degree_dot;

    double degree_d_dot;   // treadmill/reference velocity
    double degree_d_ddot;

    double torque_e;
};

class IRCController
{
private:
    AdmittanceModel admittance_;
    SlidingModeController smc_;
    NonLinearDisturbanceObserver ndo_;
    double previous_tau_e = 0.0;
public:
    IRCController(const IRCParams & params);
    double update(const RobotState& state);
};
#endif